### ISSUE TITLE
incorrect sha1: generateSignature inside CompeltePurchaseRequest (missing ShopId)

### ISSUE THREAD

**Issue by Renegade2u** [fruitcakestudio/omnipay-sisow#10]
protected function generateSignature()
    {
        return sha1(
            $this->getTransactionReference() . $this->getMerchantId() . $this->getMerchantKey()
        );
    }

should become

    protected function generateSignature()
    {
        return sha1(
            $this->getTransactionReference() . **$this->getShopId()** . $this->getMerchantId() . $this->getMerchantKey()
        );
    }

**Comment by barryvdh** [comment]
Which version are you using?
This commit should have added it already: https://github.com/fruitcake/omnipay-sisow/commit/8f7c0b8d1de910c0ede67db8a2d69c3bbe2575b5

**Comment by barryvdh** [comment]
Ah sorry, in the Complete one. Yes should probably be added there also, can you submit a PR?

**Comment by robinvalk** [comment]
Fixed with version v2.0.4, thanks for noticing @Renegade2u!
