### ISSUE TITLE
No merchantid

### ISSUE THREAD

**Issue by ziezie** [fruitcakestudio/omnipay-sisow#11]
Hi Barry,

Previously used v2.0.4 in a Laravel 5.2 site which works perfect, but having trouble with the Test beta in Laravel 5.6, keep getting error TA3210, No merchantid with the $gateway->purchase. Double checked everything, compared it with the 5.2 site, but can't figure out what is wrong. $gateway->fetchIssuers works. The Sisow example php code works with the merchantid & key so it's not those. Any clue? Thanks

**Comment by noud** [comment]
hi ziezie,
see my pull request: Fix for issue: No merchantid #11. #12
that does fix the error you got.
greetings,
Noud

**Comment by robinvalk** [comment]
Noud's PR is now merged and tagged so I'm closing the issue. Thanks!
