### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by brasileric** [fruitcakestudio/omnipay-sisow#6]
In my environment this Sisow driver gives an XML error. I found out why:

In \src\Message\AbstractResponse.php I changed this 2 lines to fix the error:

Line 25
````
$this->data = (string) $this->data->error->errormessage;
to:
$this->message = (string) $this->data->error->errormessage;
````
And line 35:
````
return $this->data;
to:
return $this->message;
````

**Comment by barryvdh** [comment]
Thanks, fixed. Not sure why it was breaking for you though.
