### ISSUE TITLE
PHPStorm auto-completion "breaks"

### ISSUE THREAD

**Issue by NickDunas** [fruitcakestudio/omnipay-sisow#9]
After installing "fruitcake/omnipay-sisow" package via composer the PHPStrom auto-completion and general PHP recognition stops working! The special coloring on the editor goes away and it is like coding on a dead notepad. After removing the package everything seems to work fine again!

I tested it using Laravel 5.4 and 5.5. To reproduce just install the package on a clean Laravel installation.

I didn't manage to find a similar issue anywhere on the web.

Any ideas why this happens using the specific package?

**Comment by NickDunas** [comment]
Commenting out $STATIC_METHOD_TYPES in .phpstorm.meta.php file of the package solves the issue! 🎉

**Comment by robinvalk** [comment]
We've not seen this issue ourselves. As you have found a workaround, I will now close this issue.
If the workaround stops working and it continues to be an issue in the future you are welcome to re-open.

Thanks!

**Comment by barryvdh** [comment]
I've deleted the meta file, which is probably old meta-file syntax. https://github.com/fruitcake/omnipay-sisow/commit/c84894523f8c57ef53c207efd5bba343c2d4dad4
